export type Mutation = {
  id: number;
  description: string;
};

export const mutations: Mutation[] = [
  { id: 1, description: "Glowing Pupils: The character's pupils emit a soft glow, visible even in daylight." },
  { id: 2, description: "Stretchable Skin: The character's skin has a rubbery texture, allowing for the stretching of limbs." },
  { id: 3, description: "Luminous Veins: The character's veins emit a soft glow beneath their skin." },
  { id: 4, description: "Nasal Appendages: The character has small, sensitive appendages on their nose." },
  { id: 5, description: "Flame-Retardant Hair: The character's hair is resistant to fire, with a faint shimmer." },
  { id: 6, description: "Chameleon Skin: Color-Shifting Scales: The character's skin has scales that change color to match surroundings." },
  { id: 7, description: "Echoing Voice: Resonant Throat: The character's throat visibly vibrates when they speak loudly." },
  { id: 8, description: "Prehensile Tail: Scaled Tail: The character's tail has scales and can be used for balance." },
  { id: 9, description: "Night Vision: Cat-Like Eyes: The character's eyes have reflective pupils, enhancing night vision." },
  { id: 10, description: "Radioactive Resistance: Glowing Veins: The character's veins emit a faint glow due to their resistance to radiation." },
  { id: 11, description: "Infrared Vision: Reptilian Eyes: The character's eyes have a reptilian appearance, aiding infrared vision." },
  { id: 12, description: "Bioelectric Touch: Crackling Fingertips: The character's fingertips emit a mild electric charge." },
  { id: 13, description: "Photosynthetic Skin: Chlorophyll Patches: The character has patches of chlorophyll on their skin." },
  { id: 14, description: "Hollow Bones: Feather-Like Hair: The character's hair takes on a feather-like texture." },
  { id: 15, description: "Extra Jointed Fingers: Insectoid Joints: The character's finger joints resemble those of insects." },
  { id: 16, description: "Psychic Resistance: Crystalline Forehead: The character has a crystalline formation on their forehead." },
  { id: 17, description: "Acidic Spit: Serpent-Like Fangs: The character has retractable, serpent-like fangs." },
  { id: 18, description: "Webbed Digits: Amphibian Webbing: The character's fingers and toes have amphibian-like webbing." },
  { id: 19, description: "Thermal Regulation: Heat-Resistant Patches: The character has patches of heat-resistant skin." },
  { id: 20, description: "Plant Communication: Vines as Hair: The character has thin, vine-like strands as hair." },
  { id: 21, description: "Magnetism: Metallic Flecks: The character's skin has metallic flecks that respond to magnetic fields." },
  { id: 22, description: "Subsonic Voice: Vibrating Ears: The character's ears visibly vibrate when they use their subsonic voice." },
  { id: 23, description: "Holographic Projection: Flickering Skin: The character's skin flickers when projecting holograms." },
  { id: 24, description: "Adhesive Skin: Sticky Pads: The character has small, adhesive pads on their palms." },
  { id: 25, description: "Antennae: Insectoid Antennae: The character has insect-like antennae on their forehead." },
  { id: 26, description: "Amphibious Lungs: Gills on Neck: The character has gill-like structures on their neck." },
  { id: 27, description: "Telekinetic Levitation: Levitating Hair: The character's hair hovers slightly when using telekinesis." },
  { id: 28, description: "Color-Changing Eyes: Shifting Iris: The character's iris changes color based on mood." },
  { id: 29, description: "Sonar Echolocation: Bat-Like Ears: The character's ears are larger and resemble those of a bat." },
  { id: 30, description: "Geiger Sense: Glowing Patches: The character has patches on their skin that glow when near radiation." },
  { id: 31, description: "Heat Absorption: Warmth-Emitting Skin: The character's skin emits a comforting warmth." },
  { id: 32, description: "Hollow Teeth: Needle-Like Teeth: The character has needle-like teeth." },
  { id: 33, description: "Levitating Objects: Floating Aura: The character's hands emit a faint glow when levitating objects." },
  { id: 34, description: "Camouflage Fur: Camouflaged Pelt: The character's fur changes color to match surroundings." },
  { id: 35, description: "Miniaturization: Shrunken Appendages: The character's limbs appear slightly smaller than normal." },
  { id: 36, description: "Poison Resistance: Toxin-Resistant Patches: The character has patches of toxin-resistant skin." },
  { id: 37, description: "Extra Eyes: Insectoid Eyes: The character has additional insect-like eyes on their forehead." },
  { id: 38, description: "Sonic Boom: Vibrating Skin: The character's skin visibly vibrates when creating a sonic boom." },
  { id: 39, description: "Photosynthetic Hair: Luminescent Strands: The character's hair glows faintly when exposed to sunlight." },
  { id: 40, description: "Exoskeleton Plates: Hardened Skin Plates: The character has small, protective plates under their skin." },
  { id: 41, description: "Quills: Porcupine-Like Quills: The character's quills are longer and more noticeable." },
  { id: 42, description: "Memory Absorption: Glowing Handprints: The character's hands leave a faint glow when in contact." },
  { id: 43, description: "Gliding Membranes: Bat-Like Wings: The character has small, bat-like wings." },
  { id: 44, description: "Density Manipulation: Shifting Mass: The character's body density visibly changes when manipulated." },
  { id: 45, description: "Pheromone Emission: Scent Glands: The character has visible scent glands on their neck." },
  { id: 46, description: "Parasitic Detox: Purifying Glow: The character emits a purifying glow when detoxifying." },
  { id: 47, description: "Elastic Organs: Visible Organs: The character's internal organs are slightly visible through their skin." },
  { id: 48, description: "Telepathic Communication: Psionic Headbands: The character has visible psionic headbands on their forehead." },
  { id: 49, description: "Waterproof Skin: Glossy Sheen: The character's skin has a glossy appearance, repelling water." },
  { id: 50, description: "Bone Spurs: Visible Spines: The character has visible spines protruding slightly from their body." },
  { id: 51, description: "Transparent Skin: Semi-Visible Veins: The character's veins are semi-visible through their skin." },
  { id: 52, description: "Ice Resistance: Frosted Hair: The character's hair appears frosted with ice crystals." },
  { id: 53, description: "Fire Absorption: Flickering Skin: The character's skin flickers like flames when absorbing fire." },
  { id: 54, description: "Winged Appendages: Feathered Wings: The character has fully feathered wings attached to their back." },
  { id: 55, description: "Crystal Growth: Shiny Crystals: The character has small, shiny crystals growing on their skin." },
  { id: 56, description: "Time Perception: Clock-like Eyes: The character's eyes have clock-like patterns." },
  { id: 57, description: "Animal Communication: Animal-Like Features: The character develops subtle animal-like features." },
  { id: 58, description: "Gravity Control: Floating Halo: The character has a faint, floating halo-like aura." },
  { id: 59, description: "Shapeshifting: Fluid Features: The character's facial features shift fluidly over time." },
  { id: 60, description: "Acid Resistance: Acid-Proof Skin: The character's skin has a glossy, acid-resistant texture." },
  { id: 61, description: "Metallic Skin: Steel-Like Sheen: The character's skin has a metallic, reflective quality." },
  { id: 62, description: "Photosensitive Eyes: Bright Pupils: The character's pupils brighten when exposed to sunlight." },
  { id: 63, description: "Magnetic Appendages: Magnetic Hands: The character's hands emit a faint magnetic pull." },
  { id: 64, description: "Airborne Adaptation: Flared Nostrils: The character's nostrils flare slightly, aiding in high-altitude breathing." },
  { id: 65, description: "Poison Emission: Faint Poison Mist: The character emits a faint, harmless mist when under stress." },
  { id: 66, description: "Energy Absorption: Glowing Tattoos: The character's tattoos glow faintly when absorbing energy." },
  { id: 67, description: "Feather Growth: Subtle Plumage: The character has feathers growing along their arms." },
  { id: 68, description: "Sound Mimicry: Vocal Changes: The character's voice shifts to mimic nearby sounds." },
  { id: 69, description: "Water Manipulation: Rippling Skin: The character's skin ripples slightly when manipulating water." },
  { id: 70, description: "Venomous Bite: Fanged Jaw: The character has venom-injecting fangs." },
  { id: 71, description: "Echo Resistance: Silencing Skin: The character's skin absorbs sound slightly, dampening echoes." },
  { id: 72, description: "Spiked Growths: Thorny Protrusions: The character has small, thorn-like protrusions." },
  { id: 73, description: "Vision Enhancements: Optical Patterns: The character's eyes develop subtle patterns for enhanced sight." },
  { id: 74, description: "Temperature Adaptation: Heat-Proof Patches: The character's skin adjusts to temperature extremes." },
  { id: 75, description: "Rocky Exterior: Hardened Skin Patches: The character's skin becomes rough and stone-like in areas." },
  { id: 76, description: "Electrical Generation: Sparkling Hands: The character's hands emit occasional sparks." },
  { id: 77, description: "Optical Camouflage: Transparent Skin: The character's skin shifts transparency for stealth." },
  { id: 78, description: "Soundproofing: Silencing Aura: The character emits a faint, sound-dampening aura." },
  { id: 79, description: "Muscle Enhancement: Enlarged Muscles: The character's muscles appear larger and more defined." },
  { id: 80, description: "Webbed Feet: Amphibian Traits: The character has webbing between their toes." },
  { id: 81, description: "Winged Arms: Feathery Appendages: The character's arms have feathers extending from them." },
  { id: 82, description: "Hardened Fingernails: Claw-Like Nails: The character's fingernails grow into claws." },
  { id: 83, description: "Night Adaptation: Enlarged Pupils: The character's pupils enlarge, aiding night vision." },
  { id: 84, description: "Venom Immunity: Resistant Skin: The character's skin becomes resilient to venomous bites." },
  { id: 85, description: "Elastic Limbs: Stretching Muscles: The character's limbs can extend slightly." },
  { id: 86, description: "Feathered Neck: Plumage Collar: The character has feathers around their neck like a collar." },
  { id: 87, description: "Crystal Fingertips: Shiny Digits: The character's fingertips have crystalline growths." },
  { id: 88, description: "Spinal Enhancements: Protruding Spines: The character's spine develops visible, protective ridges." },
  { id: 89, description: "Heat Emission: Warm Aura: The character's skin radiates warmth slightly." },
  { id: 90, description: "Acidic Aura: Protective Skin: The character's skin emits a faint, acid-neutralizing aura." },
  { id: 91, description: "Retractable Claws: Sheathed Talons: The character's claws retract like a cats." },
  { id: 92, description: "Enhanced Grip: Rough Palms: The character's palms develop a rough texture for gripping." },
  { id: 93, description: "Gliding Capabilities: Winged Shoulders: The character's shoulders grow small gliding membranes." },
  { id: 94, description: "Solar Absorption: Glowing Skin: The character's skin glows faintly after sun exposure." },
  { id: 95, description: "Metallic Growth: Small Blades: The character develops small, blade-like growths from their forearms." },
  { id: 96, description: "Insectoid Limbs: Jointed Appendages: The character's arms develop additional jointed segments." },
  { id: 97, description: "Whiskers: Sensitive Hairs: The character's face grows whisker-like hairs for sensory input." },
  { id: 98, description: "Tail Growth: Prehensile Appendage: The character develops a fully functional prehensile tail." },
  { id: 99, description: "Luminescent Nails: Glowing Fingertips: The character's fingernails glow softly in the dark." },
  { id: 100, description: "Reality Weaver: Reality Threads: The character's body is surrounded by visible threads when reshaping reality." }
]; 